<template>
    <v-container fluid>
        <v-card-title class="mt-n3">
            <v-row align-center dense class="text-h6">
                <v-col cols="auto">
                    CIDETEC Coating & Drying Simulation
                </v-col>
            </v-row>
            <v-divider class=" mt-1 mx-n5 border-opacity-50" thickness="4" color="#D4E7D4" />
        </v-card-title>


        <v-card class="mt-2" style="width: 100%;">
            <v-img src="@/assets/ai_generated_coating_2.png" contain height="auto" width="100%"/>
            <v-text class="text-left text-caption font-italic" 
                        style="position: absolute; bottom: 5px; right: 10px; color:white;">Image generated by AI</v-text>
        </v-card>
        
        <v-row>
            <v-col cols="8">
            <v-card class="mt-2" style="width: 100%; height: 100%;">
            <v-card-text>
            <h3>Inputs</h3>

            <v-row>
                <v-col cols="6">
                <v-table density="compact" style="margin-top:2%;">
                <thead>
                <tr>
                    <th class="text-left" style="width: 50%;">Parameter Name</th>
                    <th class="text-left" style="width: 40%;">Value</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="(row, index) in rows.slice(0, Math.ceil(rows.length / 2))" :key="index">
                    <td>
                        <v-icon small class="ml-0" color="grey" v-tooltip:bottom="row.tooltip">mdi-information</v-icon>
                        {{ row.parameterName }}
                    </td>
                    <td><v-text-field v-model="row.value" @change="saveRow(index)" dense hide-details solo 
                        density="compact" variant="outlined" :suffix="row.unit" /></td>
                </tr>
                </tbody>
                </v-table>
                </v-col>

                <v-col cols="6">
                <v-table density="compact" style="margin-top:2%;">
                <thead>
                    <tr>
                        <th class="text-left" style="width: 50%;">Parameter Name</th>
                        <th class="text-left" style="width: 50%;">Value</th>
                    </tr>
                </thead>
                    <tbody>
                        <tr v-for="(row, index) in rows.slice(Math.ceil(rows.length / 2))" :key="index + Math.ceil(rows.length / 2)">
                            <td>
                                <v-icon small class="ml-0" color="grey" v-tooltip:bottom="row.tooltip">mdi-information</v-icon>
                                {{ row.parameterName }}
                            </td>
                            <td>
                                <template v-if="row.parameterName === 'Drying Heat Gun'">
                                    <v-select :items="['No', 'Yes']" v-model="row.value" @change="saveRow(index + Math.ceil(rows.length / 2))" 
                                    dense hide-details solo density="compact" variant="outlined" :suffix="row.unit"/>
                                </template>
                                <template v-else>
                                    <v-text-field v-model="row.value" @change="saveRow(index + Math.ceil(rows.length / 2))" dense hide-details solo
                                    density="compact" variant="outlined" :suffix="row.unit"/>
                                </template>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
                </v-col>
            </v-row>

            <v-btn color="primary" style='margin-top:1%; width: 100%;' @click="runSimulation" 
                rounded="xl"
                density="compact">Run Simulation</v-btn>

            </v-card-text>
            </v-card>
            </v-col>

            <v-col cols="4">
            <v-card class="mt-2" style="width: 100%; height: 100%;">
                <v-card-text> 
                <h3>Outputs</h3>
                <v-table density="compact" style="margin-top:2%;">
                    <thead>
                        <tr>
                            <th class="text-left" style="width: 50%;">Parameter Name</th>
                            <th class="text-left" style="width: 50%;">Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(output, index) in outputs.slice(0, Math.ceil(outputs.length))" :key="index">
                            <td>
                                <v-icon small class="ml-0" color="grey" v-tooltip:bottom="output.tooltip">mdi-information</v-icon>
                                {{ output.parameterName }}</td>
                            <td>
                                <v-text-field v-model="output.value" dense hide-details readonly
                                    density="compact" variant="outlined" :suffix="output.unit"/>
                            </td>
                        </tr>
                    </tbody>
                    </v-table>
                </v-card-text>
            </v-card>
            </v-col>
        </v-row>

        </v-container>
        </template>

        <script>
        import axios from 'axios';
        import Swal from 'sweetalert2'

        export default {
        name: 'ManufacturingCoatingView',
        data() {
            return {
            showParametersRange: false,
            rows: [
                { parameterName: 'Coating Line Speed', unit: 'm/min', value: 1.5, 
                    min_value: 1.4, max_value: 1.6, message:"Coating line speed should be between 1.4m/min and 1.6m/min",
                    tooltip: "The speed of the coating line in meters per minute" },
                { parameterName: 'Coating Gap', unit: 'µm', value: 325, 
                    min_value: 293, max_value: 353, message:"Coating gap should be between 293µm and 353µm", 
                    tooltip: "The gap between the coating head and the substrate in micrometers" },
                { parameterName: 'Drying IR', unit: '%', value: 100, 
                    min_value: 80, max_value: 100, message:"Drying IR should be between 80% and 100%", 
                    tooltip: "The intensity of the infrared drying system in percentage" },
                { parameterName: 'Oven1 Temperature', unit: '°C', value: 90, 
                    min_value: 81, max_value: 98, message:"Oven1 temperature should be between 81°C and 98°C", 
                    tooltip: "The temperature of the first oven in degrees Celsius" },
                { parameterName: 'Oven1 Fan', unit: 'rpm', value: 550, 
                    min_value: 495, max_value: 625, message:"Oven1 Fan should be between 495rpm and 625rpm", 
                    tooltip: "The fan speed of the first oven in revolutions per minute" },
                { parameterName: 'Oven2 Temperature', unit: '°C', value: 85, 
                    min_value: 77, max_value: 92, message:"Oven2 temperature should be between 77°C and 92°C", 
                    tooltip: "The temperature of the second oven in degrees Celsius" },
                { parameterName: 'Oven2 Fan', unit: 'rpm', value: 525, 
                    min_value: 473, max_value: 600, message:"Oven2 Fan should be between 473rpm and 600rpm", 
                    tooltip: "The fan speed of the second oven in revolutions per minute" },
                { parameterName: 'Oven3 Temperature', unit: '°C', value: 80, 
                    min_value: 72, max_value: 87, message:"Oven3 temperature should be between 72°C and 87°C", 
                    tooltip: "The temperature of the third oven in degrees Celsius" },
                { parameterName: 'Oven3 Fan', unit: 'rpm', value: 500, 
                    min_value: 450, max_value: 575, message:"Oven3 Fan should be between 450rpm and 575rpm", 
                    tooltip: "The fan speed of the third oven in revolutions per minute" },
                { parameterName: 'Drying Heat Gun', unit: '-', value: 'No', 
                    min_value: 'No', max_value: 'Yes', message:"heat gun", 
                    tooltip: "Use of a heat gun for drying" },
            ],
            outputs:[
                { parameterName: 'Electrode Loading', unit: 'mAh/cm2', value: 4, 
                tooltip: "The loading of the electrode in milliampere-hours per square centimeter",
                },
                { parameterName: 'Electrode Dryness', unit: '%', value: 80, 
                tooltip: "The probability to be totally dry after drying",
                },
            ]
            }
        },
        methods: {
            saveRow(index) {
                // console.log('Row saved:', this.rows[index]);
            },
            validate_inputs() {
                return new Promise((resolve, reject) => {
                    let warning_message = "";
                    let show_warning = false;

                    for (let index = 0; index < this.rows.length; index++) {
                        const element = this.rows[index];
                        if (element.parameterName === 'Drying Heat Gun') {
                            continue;
                        } else if (element.value < element.min_value || element.value > element.max_value) {
                            warning_message += "<br>" + element.message;
                            show_warning = true;
                        }
                    }

                    if (show_warning) {
                        Swal.fire({
                            icon: 'warning',
                            title: 'Input values out of range',
                            html: warning_message,
                            confirmButtonText: 'Continue',
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            cancelButtonColor: '#d33',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            resolve(); // Continue simulation after user closes the warning
                        } else {
                        reject(); // Stop simulation if user cancels
                        }   
                    });
                    } else {
                        resolve(); // No warnings, continue immediately
                    }
                });
            },
            runSimulation(){
                this.validate_inputs()
                .then(() => {
                    return this.$axiosProteoDA.post('/manufacturing/coating/', this.rows)
                })
                .then((res) => {
                    const data = res.data
                    this.outputs[0].value = parseFloat(data['loading_value']).toFixed(2)
                    this.outputs[1].value = parseFloat(data['dyring_value']).toFixed(2)
                })
            }, 
        }
    }
    </script>
